### PR TITLE
Add automation test environment with GithubAction for PHP 0.8

### PR DESCRIPTION
**Pull request by thanhthanh-yen**
Automation test environment includes:

- Setup environment
- Run samples
- Test with test sets

### CODE REVIEW

**Comment by chiendh** [comment]
@thanhthanh-yen 

I have checked you PR.
It can't finish install environment step because SWIG installation step is failed.
Please check and update again.
I have short check your installation script. Error cause by SWIG URL was changed.
You can't get SWIG source by old URL. 

Please check again.

**Comment by thanhthanh-yen** [comment]
@chiendh 

Thank you for your comment.
The site might be down in this morning but now it comes back.
I have tested again and the result is OK.

Thanks,

**Comment by knonomura** [comment]
@thanhthanh-yen 
Thank you for your creation with GitHub Actions.
I'll check it.

**Comment by knonomura** [comment]
I checked your environment.
I can successfully run it.
So, I merge this PR.
Thank you.

**Pull request merged**
